### ISSUE TITLE
404 link

### ISSUE THREAD

**Issue by shawn0915** [IvorySQL/ivorysql_docs#33]
https://docs.ivorysql.org/cn/ivorysql-doc/beta/beta/3#%E6%96%B0%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97

您可以访问我们的 [地址](https://xn--deploy-preview-83ivorysql-0u5o.netlify.app/zh-CN/)

**Comment by DutMsn** [comment]
这个地址看起来是正确的，没有出现404的情况，是有什么问题吗？

**Comment by DutMsn** [comment]
> https://docs.ivorysql.org/cn/ivorysql-doc/beta/beta/3#%E6%96%B0%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97
> 
> 您可以访问我们的 [地址](https://xn--deploy-preview-83ivorysql-0u5o.netlify.app/zh-CN/)
上面的地址看起来是正确的，没有出现404的情况，下面的地址是点击哪里跳转的，可以详细说一下吗

**Comment by shawn0915** [comment]
![图片](https://github.com/IvorySQL/ivorysql_docs/assets/17957066/3817b2ff-438e-48d9-869b-2226fd78ebf8)

@DutMsn 这里

**Comment by DutMsn** [comment]
> ![图片](https://user-images.githubusercontent.com/17957066/279236561-3817b2ff-438e-48d9-869b-2226fd78ebf8.png)
> 
> @DutMsn 这里

收到，我们会尽快修复。

**Comment by DutMsn** [comment]
#39
