### ISSUE TITLE
table format

### ISSUE THREAD

**Issue by shawn0915** [IvorySQL/ivorysql_docs#34]
https://docs.ivorysql.org/cn/ivorysql-doc/beta/beta/4#pg_stat_activity

表3.pg_stat_activity 视图

表格样式被破坏

**Comment by DutMsn** [comment]
> https://docs.ivorysql.org/cn/ivorysql-doc/beta/beta/4#pg_stat_activity
> 
> 表3.pg_stat_activity 视图
> 
> 表格样式被破坏

感谢您的测试，我们会尽快修复这个问题。

**Comment by DutMsn** [comment]
#38
