### ISSUE TITLE
页面内超链接的链接地址为zhihu跳转地址

### ISSUE THREAD

**Issue by YunheXu** [IvorySQL/ivorysql_docs#42]
https://docs.ivorysql.org/cn/ivorysql-doc/beta/beta/9#%E8%BF%81%E7%A7%BB%E5%B7%A5%E5%85%B7ora2pg
该页面内超链接的链接地址为zhihu跳转地址
![image](https://github.com/IvorySQL/ivorysql_docs/assets/62319153/91b46297-38c3-459b-8a91-afddeabe4ac8)
![image](https://github.com/IvorySQL/ivorysql_docs/assets/62319153/d039f99d-3914-4780-b961-617ef12199c5)

**Comment by DutMsn** [comment]
#43 感谢您的测试！
